FROM python:3.13-slim

WORKDIR /app
COPY backend/ .
COPY requirements.txt .
RUN pip install -r requirements.txt

# Копируем media и static из корня проекта
COPY media/ /app/media/
COPY static/ /app/static/

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "your_project.wsgi:application"]
