# Generated by Django 5.1.7 on 2025-03-21 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_alter_block_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemoderationlog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
    ]
