# Generated by Django 5.1.7 on 2025-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemoderationlog_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='block_covers/', verbose_name='Обложка блока'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='Обложка курса'),
        ),
    ]
